
kind: StatefulSet
apiVersion: apps/v1
metadata:
    namespace: default
    name: crainst01
    labels:
        operator: source01
        instance: crainst01
spec:
    replicas: 1
    serviceName: crainst01
    selector:
        matchLabels:
            instance: crainst01
    template:
        metadata:
            name: crainst01
            labels:
                operator: source01
                instance: crainst01
        spec:
            containers:
            - name: crainst01
              image: mdzwart/cra-net3.1:latest
              ports:
              - containerPort: 1500
              env:
              - name: AZURE_STORAGE_CONN_STRING
                value: "DefaultEndpointsProtocol=https;AccountName=vertexstore;AccountKey=3BMGVlrXZq8+NE9caC47KDcpZ8X59vvxFw21NLNNLFhKGgmA8Iq+nr7naEd7YuGGz+M0Xm7dSUhgkUN5N9aMLw==;EndpointSuffix=core.windows.net"
              args: ["crainst01", "1500"] #CRA instance name crainst01, exposed on port 1500
              #resources: #requests #cpu "500m" #hotfix to prevent two instances on the same node (assuming 1m cpu total)
---

kind: StatefulSet
apiVersion: apps/v1
metadata:
    namespace: default
    name: crainst02
    labels:
        operator: map01
        instance: crainst02
spec:
    replicas: 1
    serviceName: crainst02
    selector:
        matchLabels:
            instance: crainst02
    template:
        metadata:
            name: crainst02
            labels:
                operator: map01
                instance: crainst02
        spec:
            containers:
            - name: crainst02
              image: mdzwart/cra-net3.1:latest
              ports:
              - containerPort: 1500
              env:
              - name: AZURE_STORAGE_CONN_STRING
                value: "DefaultEndpointsProtocol=https;AccountName=vertexstore;AccountKey=3BMGVlrXZq8+NE9caC47KDcpZ8X59vvxFw21NLNNLFhKGgmA8Iq+nr7naEd7YuGGz+M0Xm7dSUhgkUN5N9aMLw==;EndpointSuffix=core.windows.net"
              args: ["crainst02", "1500"] #CRA instance name crainst02, exposed on port 1500
              #resources: #requests #cpu "500m" #hotfix to prevent two instances on the same node (assuming 1m cpu total)
---

kind: StatefulSet
apiVersion: apps/v1
metadata:
    namespace: default
    name: crainst03
    labels:
        operator: map01
        instance: crainst03
spec:
    replicas: 1
    serviceName: crainst03
    selector:
        matchLabels:
            instance: crainst03
    template:
        metadata:
            name: crainst03
            labels:
                operator: map01
                instance: crainst03
        spec:
            containers:
            - name: crainst03
              image: mdzwart/cra-net3.1:latest
              ports:
              - containerPort: 1500
              env:
              - name: AZURE_STORAGE_CONN_STRING
                value: "DefaultEndpointsProtocol=https;AccountName=vertexstore;AccountKey=3BMGVlrXZq8+NE9caC47KDcpZ8X59vvxFw21NLNNLFhKGgmA8Iq+nr7naEd7YuGGz+M0Xm7dSUhgkUN5N9aMLw==;EndpointSuffix=core.windows.net"
              args: ["crainst03", "1500"] #CRA instance name crainst03, exposed on port 1500
              #resources: #requests #cpu "500m" #hotfix to prevent two instances on the same node (assuming 1m cpu total)
---

kind: StatefulSet
apiVersion: apps/v1
metadata:
    namespace: default
    name: crainst04
    labels:
        operator: aggregate01
        instance: crainst04
spec:
    replicas: 1
    serviceName: crainst04
    selector:
        matchLabels:
            instance: crainst04
    template:
        metadata:
            name: crainst04
            labels:
                operator: aggregate01
                instance: crainst04
        spec:
            containers:
            - name: crainst04
              image: mdzwart/cra-net3.1:latest
              ports:
              - containerPort: 1500
              env:
              - name: AZURE_STORAGE_CONN_STRING
                value: "DefaultEndpointsProtocol=https;AccountName=vertexstore;AccountKey=3BMGVlrXZq8+NE9caC47KDcpZ8X59vvxFw21NLNNLFhKGgmA8Iq+nr7naEd7YuGGz+M0Xm7dSUhgkUN5N9aMLw==;EndpointSuffix=core.windows.net"
              args: ["crainst04", "1500"] #CRA instance name crainst04, exposed on port 1500
              #resources: #requests #cpu "500m" #hotfix to prevent two instances on the same node (assuming 1m cpu total)
---

kind: StatefulSet
apiVersion: apps/v1
metadata:
    namespace: default
    name: crainst05
    labels:
        operator: aggregate01
        instance: crainst05
spec:
    replicas: 1
    serviceName: crainst05
    selector:
        matchLabels:
            instance: crainst05
    template:
        metadata:
            name: crainst05
            labels:
                operator: aggregate01
                instance: crainst05
        spec:
            containers:
            - name: crainst05
              image: mdzwart/cra-net3.1:latest
              ports:
              - containerPort: 1500
              env:
              - name: AZURE_STORAGE_CONN_STRING
                value: "DefaultEndpointsProtocol=https;AccountName=vertexstore;AccountKey=3BMGVlrXZq8+NE9caC47KDcpZ8X59vvxFw21NLNNLFhKGgmA8Iq+nr7naEd7YuGGz+M0Xm7dSUhgkUN5N9aMLw==;EndpointSuffix=core.windows.net"
              args: ["crainst05", "1500"] #CRA instance name crainst05, exposed on port 1500
              #resources: #requests #cpu "500m" #hotfix to prevent two instances on the same node (assuming 1m cpu total)
---

kind: StatefulSet
apiVersion: apps/v1
metadata:
    namespace: default
    name: crainst06
    labels:
        operator: sink01
        instance: crainst06
spec:
    replicas: 1
    serviceName: crainst06
    selector:
        matchLabels:
            instance: crainst06
    template:
        metadata:
            name: crainst06
            labels:
                operator: sink01
                instance: crainst06
        spec:
            containers:
            - name: crainst06
              image: mdzwart/cra-net3.1:latest
              ports:
              - containerPort: 1500
              env:
              - name: AZURE_STORAGE_CONN_STRING
                value: "DefaultEndpointsProtocol=https;AccountName=vertexstore;AccountKey=3BMGVlrXZq8+NE9caC47KDcpZ8X59vvxFw21NLNNLFhKGgmA8Iq+nr7naEd7YuGGz+M0Xm7dSUhgkUN5N9aMLw==;EndpointSuffix=core.windows.net"
              args: ["crainst06", "1500"] #CRA instance name crainst06, exposed on port 1500
              #resources: #requests #cpu "500m" #hotfix to prevent two instances on the same node (assuming 1m cpu total)
---

kind: StatefulSet
apiVersion: apps/v1
metadata:
    namespace: default
    name: crainst07
    labels:
        operator: coordinator01
        instance: crainst07
spec:
    replicas: 1
    serviceName: crainst07
    selector:
        matchLabels:
            instance: crainst07
    template:
        metadata:
            name: crainst07
            labels:
                operator: coordinator01
                instance: crainst07
        spec:
            containers:
            - name: crainst07
              image: mdzwart/cra-net3.1:latest
              ports:
              - containerPort: 1500
              env:
              - name: AZURE_STORAGE_CONN_STRING
                value: "DefaultEndpointsProtocol=https;AccountName=vertexstore;AccountKey=3BMGVlrXZq8+NE9caC47KDcpZ8X59vvxFw21NLNNLFhKGgmA8Iq+nr7naEd7YuGGz+M0Xm7dSUhgkUN5N9aMLw==;EndpointSuffix=core.windows.net"
              args: ["crainst07", "1500"] #CRA instance name crainst07, exposed on port 1500
              #resources: #requests #cpu "500m" #hotfix to prevent two instances on the same node (assuming 1m cpu total)
---
