
kind: Deployment
apiVersion: apps/v1
metadata:
    namespace: default
    name: crainst01
    labels:
        operator: source01
        instance: crainst01
spec:
    replicas: 1
    selector:
        matchLabels:
            instance: crainst01
    template:
        metadata:
            name: crainst01
            labels:
                operator: source01
                instance: crainst01
        spec:
            containers:
            - name: crainst01
              image: mdzwart/cra-net2.1:latest
              ports:
              - containerPort: 1500
              env:
              - name: AZURE_STORAGE_CONN_STRING
                value: "DefaultEndpointsProtocol=https;AccountName=vertexstore;AccountKey=3BMGVlrXZq8+NE9caC47KDcpZ8X59vvxFw21NLNNLFhKGgmA8Iq+nr7naEd7YuGGz+M0Xm7dSUhgkUN5N9aMLw==;EndpointSuffix=core.windows.net"
              args: ["crainst01", "1500"] #CRA instance name crainst01, exposed on port 1500
              #resources: #requests #cpu "500m" #hotfix to prevent two instances on the same node (assuming 1m cpu total)
---

kind: Deployment
apiVersion: apps/v1
metadata:
    namespace: default
    name: crainst02
    labels:
        operator: sink01
        instance: crainst02
spec:
    replicas: 1
    selector:
        matchLabels:
            instance: crainst02
    template:
        metadata:
            name: crainst02
            labels:
                operator: sink01
                instance: crainst02
        spec:
            containers:
            - name: crainst02
              image: mdzwart/cra-net2.1:latest
              ports:
              - containerPort: 1500
              env:
              - name: AZURE_STORAGE_CONN_STRING
                value: "DefaultEndpointsProtocol=https;AccountName=vertexstore;AccountKey=3BMGVlrXZq8+NE9caC47KDcpZ8X59vvxFw21NLNNLFhKGgmA8Iq+nr7naEd7YuGGz+M0Xm7dSUhgkUN5N9aMLw==;EndpointSuffix=core.windows.net"
              args: ["crainst02", "1500"] #CRA instance name crainst02, exposed on port 1500
              #resources: #requests #cpu "500m" #hotfix to prevent two instances on the same node (assuming 1m cpu total)
---
